### ISSUE TITLE
can`t convert model in visual studio

### ISSUE THREAD

**Issue by dorademon** [Microsoft/vs-tools-for-ai#19]
HI, I want  to convert a scikit-learn model to onnx,but I dont   now how to set  up the  input_featrues  parameters. Please help me,thanks :)

my  model  featrues : 
Sepal Length   float   1
Sepal Width   float    1
Petal Length   float    1
Petal Width    float    1

Here are the error logs :

System.Exception: D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\sklearn\base.py:311: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "C:\USERS\H00316469\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_04A81442\EXTENSIONS\Y2LMQEZR.VBA\RuntimeSDK\model\model_converter_cli.py", line 203, in convert_sklearn_to_onnx
    model_onnx = convert_sklearn(model_sklearn, extra_args.get(paramname_graph_name), input_features)
  File "D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\winmltools\convert\main.py", line 20, in convert_sklearn
    return _convert_sklearn(model, name, input_features)
  File "D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\onnxmltools\convert\sklearn\convert.py", line 109, in convert
    nodes += _convert_sklearn_node(context, model, node_inputs)
  File "D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\onnxmltools\convert\sklearn\convert.py", line 159, in _convert_sklearn_node
    return _do_convert(context, converter, node, inputs)
  File "D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\onnxmltools\convert\sklearn\convert.py", line 148, in _do_convert
    node = converter.convert(context, sk_node, inputs)
  File "D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\onnxmltools\convert\sklearn\GLMClassifierConverter.py", line 63, in convert
    class_labels = utils.cast_list(int, classes)
  File "D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\onnxmltools\convert\common\utils.py", line 144, in cast_list
    return [type(item) for item in items]
  File "D:\sofatware\microsoft Visual Studio\shared\Python36_64\lib\site-packages\onnxmltools\convert\common\utils.py", line 144, in <listcomp>
    return [type(item) for item in items]
ValueError: invalid literal for int() with base 10: 'Iris-setosa'

**Comment by dorademon** [comment]
@simplywilson    Many thanks！

**Comment by tocean** [comment]
Could you share you model file please?

**Comment by dorademon** [comment]
@tocean 
Thanks for your attention, I can't share my model file because of information security.
the main question is  
how can I  set the Extra arguments (Graph name/Input features including name,type and shape)？ docs of tools for AI doesn't tell this.

**Comment by tocean** [comment]
It depends on the input of your model. For this case, if the input feature is a float array with shape [4], I think the following should work. 
![image](https://user-images.githubusercontent.com/4133758/40653429-b00ffcd8-636d-11e8-9e61-4a6616029612.png)
